# Generated by Django 5.1.3 on 2024-12-11 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CleanSMRs_eCommerce', '0002_activationtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('duration_months', models.IntegerField(blank=True, choices=[(12, '1 year'), (24, '2 years'), (36, '3 years')], verbose_name='Duration')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(blank=True, choices=[('physical_product', 'Physical Product'), ('data_access', 'Data Access')], max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('image_path', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_price_id', models.CharField(blank=True, max_length=50, verbose_name='Stripe Price ID')),
                ('plan', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='CleanSMRs_eCommerce.plan', verbose_name='Plan')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=40)),
                ('date_placed', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], max_length=20)),
                ('order_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CleanSMRs_eCommerce.product', verbose_name='Product')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CleanSMRs_eCommerce.order', verbose_name='Order')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CleanSMRs_eCommerce.plan', verbose_name='Plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
